plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
env:
  root: true
  es6: true
  node: true
  browser: true
rules:
  prettier/prettier: error
  no-inline-styles: false
